[package]
name = "substrate-lite"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
license = "GPL3"    # TODO: we're copy-pasting code from Substrate, so it must be GPL; can probably be removed if we remove all of Substrate's code
edition = "2018"
keywords = ["blockchain", "peer-to-peer"]
default-run = "full-node"

[features]
default = ["database-sled", "os-networking"]
database-sled = ["sled"]
os-networking = [
    "async-std",
    "async-tls",
    "libp2p/dns",
    "libp2p/tcp-async-std",
    "libp2p/websocket",
    "soketto",
    "url",
    "webpki"
]
wasm-bindings = [
    "chrono/wasmbind",
    "futures-timer/wasm-bindgen",
    "js-sys",
    "rand/wasm-bindgen",
    "wasm-bindgen",
    "wasm-bindgen-futures",
    "web-sys"
]

[[bin]]
name = "database-explorer"
path = "bin/database-explorer.rs"
required-features = ["database-sled"]

[[bin]]
name = "full-node"
path = "bin/full-node.rs"
required-features = ["database-sled", "os-networking"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ansi_term = "0.12.1"
app_dirs = "1.2.1"
arrayvec = "0.5.1"
async-trait = "0.1"
atomic = "0.4.6"
blake2-rfc = { version = "0.2.18", default-features = false }
chrono = { version = "0.4", features = ["serde"] }   # TODO: remove serde feature
derive_more = "0.99.7"
ed25519-dalek = { version = "1.0.0", default-features = false, features = ["alloc", "batch"] }
either = "1.5.3"
env_logger = "0.7.1"
fnv = "1.0"
futures = "0.3.1"   # TODO: should be default-features = false, but we use some std-only types at the moment
futures_codec = "0.3.3"
futures-timer = "3.0"
hashbrown = { version = "0.7.0", default-features = false, features = ["serde"] }   # TODO: remove serde feature
hex = { version = "0.4.2", default-features = false }
ip_network = "0.3.4"
libsecp256k1 = "0.3.5"
lru = "0.5.3"   # TODO: audit the unsafe code in that crate
merlin = { version = "2.0", default-features = false }
num-bigint = "0.2.3"
num-rational = "0.2.2"
num-traits = "0.2.8"
parking_lot = "0.10.2"
parity-scale-codec = { version = "1.0.0", features = ["derive"] }
pin-project = "0.4"
prost = "0.6.1"
rand = "0.7"
schnorrkel = { version = "0.9.1", default-features = false }
send_wrapper = "0.4.0"
serde = { version = "1.0.101", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0.48", default-features = false, features = ["alloc"] }
slab = "0.4.2"
smallvec = "0.6.10"
terminal_size = "0.1.12"
tiny-keccak = { version = "2.0", features = ["keccak"] }
twox-hash = "1.5.0"
unsigned-varint = { version = "0.3.1", features = ["futures", "futures-codec"] }
wasmi = "0.6.2"
wasm-timer = "0.2.4"

# `database-sled` feature
sled = { version = "0.31.0", features = ["compression"], optional = true }

# `os-networking` feature
async-std = { version = "1.6.2", optional = true }
async-tls = { version = "0.7.0", optional = true }
soketto = { version = "0.4.0", optional = true }
url = { version = "2.1.1", optional = true }
webpki = { version = "0.21.0", optional = true }

# `wasm-bindings` feature
console_error_panic_hook = "0.1.6"
js-sys = { version = "0.3.44", optional = true }
wasm-bindgen = { version = "0.2.67", optional = true }
wasm-bindgen-futures = { version = "0.4.17", optional = true }
web-sys = { version = "0.3.44", optional = true, features = ["console", "DomException", "IdbDatabase", "IdbFactory", "IdbObjectStore", "IdbOpenDbRequest", "IdbRequest", "IdbTransaction", "IdbTransactionMode", "IdbVersionChangeEvent", "Window"] }

# BELOW: DEPENDENCIES TO REMOVE
# TODO:
anyhow = "1.0.31"  # TODO: wasmtime returns these errors for some reason
bitflags = "1.2.1"  # TODO: I hate bitflags
blake2 = "0.8.1"  # TODO: should be merged with blake2-rfc
bytes = "0.5.0"  # TODO: I hate bytes
impl-serde = "0.2.3"  # TODO: that looks like a hack
libp2p-wasm-ext = { version = "0.20.1", features = ["websocket"] }  # TODO: activating the "websocket" feature because the libp2p front doesn't provide a way; https://github.com/libp2p/rust-libp2p/pull/1718
primitive-types = { version = "0.6.2", default-features = false, features = ["codec", "serde", "std"] } # TODO: nothing wrong with this one, but ideally don't use parity crates
sc-peerset = { git = "https://github.com/paritytech/substrate", rev = "16fdfc4a80a14a26221d17b8a1b9a95421a1576c" }
void = "1.0"    # TODO: remove

[dependencies.libp2p]
version = "0.22.0"
default-features = false
features = ["identify", "kad", "mdns", "mplex", "noise", "ping", "request-response", "wasm-ext", "yamux"]

[target.'cfg(target_arch = "x86_64")'.dependencies]
# `wasmtime` feature
# TODO: enable by default, but requires some nightly-only features
wasmtime = { version = "0.18.0", default-features = false, optional = true }

[build-dependencies]
prost-build = "0.6.1"

[dev-dependencies]
async-std = "1.6.2"
# TODO: remove
libp2p = { version = "0.22.0", default-features = false, features = ["secio"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[profile.dev]
opt-level = 2
panic = "abort"
[profile.dev.package."*"]
opt-level = 3

# The `test` profile mimics the `dev` profile to avoid recompilations.
[profile.test]
opt-level = 2
[profile.test.package."*"]
opt-level = 3

[profile.release]
panic = "abort"
lto = true
#strip = "symbols"      # TODO: uncomment once stable
