[package]
name = "substrate-lite"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
license = "GPL3"    # TODO: we're copy-pasting code from Substrate, so it must be GPL; can probably be removed if we remove all of Substrate's code
edition = "2018"
default-run = "node"

[dependencies]
ansi_term = "0.12.1"
app_dirs = "1.2.1"
arrayvec = "0.5.1"
async-trait = "0.1"
blake2-rfc = { version = "0.2.18", default-features = false }
chrono = { version = "0.4", features = ["serde"] }   # TODO: remove serde feature
derive_more = "0.99.7"
either = "1.5.3"
env_logger = "0.7.1"
fnv = "1.0"
futures = "0.3.1"   # TODO: should be default-features = false, but we use some std-only types at the moment
futures_codec = "0.3.3"
futures-timer = "3.0"
hashbrown = { version = "0.7.0", default-features = false, features = ["serde"] }   # TODO: remove serde feature
hex = { version = "0.4.2", default-features = false }
ip_network = "0.3.4"
jsonrpsee = { git = "https://github.com/paritytech/jsonrpsee" }
libsecp256k1 = "0.3.5"
lru = "0.5.3"   # TODO: audit the unsafe code in that crate
merlin = { version = "2.0", default-features = false }
parking_lot = "0.10.2"
parity-scale-codec = { version = "1.0.0", features = ["derive"] }
pin-project = "0.4"
prost = "0.6.1"
rand = "0.7"
schnorrkel = { version = "0.9.1", default-features = false }
serde = { version = "1.0.101", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0.48", default-features = false, features = ["alloc"] }
slab = "0.4.2"
sled = { version = "0.31.0", features = ["compression"] }
smallvec = "0.6.10"
terminal_size = "0.1.12"
tiny-keccak = { version = "2.0", features = ["keccak"] }
twox-hash = "1.5.0"
unsigned-varint = { version = "0.3.1", features = ["futures", "futures-codec"] }
wasmi = "0.6.2"
wasm-timer = "0.2.4"

# BELOW: DEPENDENCIES TO REMOVE
# TODO:
anyhow = "1.0.31"  # TODO: wasmtime returns these errors for some reason
async-std = "1.6"  # TODO: we use it as a quick hack for spawning a task
bitflags = "1.2.1"  # TODO: I hate bitflags
blake2 = "0.8.1"  # TODO: should be merged with blake2-rfc
bytes = "0.5.0"  # TODO: I hate bytes
impl-serde = "0.2.3"  # TODO: that looks like a hack
log = "0.4"  # TODO: we don't need logging
primitive-types = { version = "0.6.2", default-features = false, features = ["codec", "serde", "std"] } # TODO: nothing wrong with this one, but ideally don't use parity crates
sc-peerset = { git = "https://github.com/paritytech/substrate", rev = "16fdfc4a80a14a26221d17b8a1b9a95421a1576c" }
void = "1.0"    # TODO: remove

[dependencies.libp2p]
version = "0.22.0"
default-features = false
features = ["dns", "identify", "kad", "mdns", "mplex", "noise", "ping", "request-response", "tcp-async-std", "wasm-ext", "websocket", "yamux"]

[target.'cfg(target_arch = "x86_64")'.dependencies]
wasmtime = { version = "0.18.0", default-features = false }

[build-dependencies]
prost-build = "0.6.1"

[dev-dependencies]
async-std = "1.6.2"
libp2p = { version = "0.21.1", default-features = false, features = ["secio"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[profile.dev]
opt-level = 2
panic = "abort"
[profile.dev.package."*"]
opt-level = 3

# The `test` profile mimics the `dev` profile to avoid recompilations.
[profile.test]
opt-level = 2
[profile.test.package."*"]
opt-level = 3

[profile.release]
panic = "abort"
lto = true
#strip = "symbols"      # TODO: uncomment once stable
