[package]
name = "substrate-lite"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
license = "GPL3"    # TODO: we're copy-pasting code from Substrate, so it must be GPL; can probably be removed if we remove all of Substrate's code
edition = "2018"

[dependencies]
ansi_term = "0.12.1"
blake2 = "0.8.1"
blake2-rfc = { version = "0.2.18", default-features = false }
derive_more = "0.99.7"
env_logger = "0.4"
fnv = "1.0"
futures = "0.3.1"   # TODO: should be default-features = false, but we use some std-only types at the moment
futures_codec = "0.3.3"
futures-timer = "3.0"
hashbrown = { version = "0.7.0", default-features = false, features = ["serde"] }
ip_network = "0.3.4"
jsonrpsee = { git = "https://github.com/paritytech/jsonrpsee" }
log = "0.4"
parity-db = "0.1.2"
parity-scale-codec = { version = "1.0.0", features = ["derive"] }
parity-wasm = "0.41.0"
pin-project = "0.4"
prost = "0.6.1"
rand = "0.7"
serde = { version = "1.0.101", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0.48", default-features = false, features = ["alloc"] }
smallvec = "0.6.10"
twox-hash = "1.5.0"
unsigned-varint = { version = "0.3.1", features = ["futures", "futures-codec"] }
wasmi = "0.6.2"
wasm-timer = "0.2.4"

# BELOW: DEPENDENCIES TO REMOVE
# TODO:
bitflags = "1.2.1"  # TODO: I hate bitflags
bytes = "0.5.0"  # TODO: I hate bytes
impl-serde = "0.2.3"  # TODO: that looks like a hack
primitive-types = { version = "0.6.2", default-features = false, features = ["codec", "serde", "std"] } # TODO: nothing wrong with this one, but ideally don't use parity crates
sc-peerset = "2.0.0-alpha.3"
void = "1.0"    # TODO: remove

[dependencies.libp2p]
version = "0.19.1"
default-features = false
features = ["dns", "identify", "kad", "mdns", "mplex", "noise", "ping", "tcp-async-std", "wasm-ext", "websocket", "yamux"]

[build-dependencies]
prost-build = "0.6.1"

[dev-dependencies]
async-std = "~1.5.0"
libp2p = { version = "0.19.1", default-features = false, features = ["secio"] }

[profile.dev]
opt-level = 1
panic = "abort"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
panic = "abort"
lto = true
