[package]
name = "avail-light"
version = "1.5.0"
authors = ["Avail Team"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
avail-subxt = { git = "https://github.com/availproject/avail.git", tag = "v1.6.1-rc3" }
chrono = "0.4.19"
dusk-plonk = { git = "https://github.com/availproject/plonk.git", tag = "v0.12.0-polygon-2" }
futures = { version = "0.3.15", default-features = false, features = ["std", "thread-pool"] }
futures-util = "0.3.17"
hyper = { version = "0.14.23", features = ["full", "http1"] }
hyper-tls = "0.5.0"
kate-recovery = { version = "0.8", git = "https://github.com/availproject/avail-core", tag = "da-primitives/v0.4.6" }
num = "0.4.0"
rand = "0.8.4"
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
tokio = { version = "1.21.2", features = ["full"] }
tokio-stream = "0.1.11"
url = "2.2.2"

anyhow = "1.0.41"
async-std = { version = "1.12.0", features = ["attributes"] }
clap = { version = "4.3.0", features = ["cargo"] }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "full", "bit-vec"] }
confy = "0.4.0"
ed25519-dalek = "1.0.1"
hex = "0.4"
libipld = { version = "0.12.0", default-features = false, features = ["dag-cbor"] }
libp2p = { version = "0.51.0", features = ["full"] }
multihash = { version = "0.14.0", default-features = false, features = ["blake3", "sha3"] }
num_cpus = "1.13.0"
prometheus-client = "0.19.0"
rocksdb = { version = "0.17.0", features = ["snappy", "multi-threaded-cf"] }
scale-info = { version = "2.0.0", features = ["bit-vec"] }
smallvec = "1.6.1"
sp-core = "6.0.0"
tempdir = "0.3.7"
thiserror = "1.0.37"
threadpool = "1.8.1"
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.15", features = ["json"] }
warp = "0.3.2"

async-trait = "0.1.66"
base64 = "0.21.0"
hex-literal = "0.4.0"
itertools = "0.10.5"
mockall = "0.11.3"
openssl = { version = "0.10", features = ["vendored"] }
pcap = "1.1.0"
uuid = { version = "1.3.4", features = ["v4", "fast-rng", "macro-diagnostics"] }
void = "1.0.2"

[features]
network-analysis = []
api-v2 = []
default = []

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"

[dev-dependencies]
proptest = "1.0.0"
test-case = "1.2.3"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
