http_server_host = '0.0.0.0'
avail_path = "/var/lib/avail-light/avail_path"
http_server_port = 7000
port = 37000
log_level = 'INFO'
log_format_json = true

max_parallel_fetch_tasks = 8
query_proof_rpc_parallel_tasks = 10
connection_idle_timeout = 10
sync_blocks_depth = 0

confidence = 92.0
