name: deploy

on:
  push:
    branches:    
      - master

jobs:
  build-push-docker-image:
    name: Build and push passive node Docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: tomaka/substrate-lite/node
        tag_with_ref: true
