name: Releaser
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'

jobs:

  binary_linux_amd64:
    runs-on: ubuntu-latest
    steps:
         - uses: actions/checkout@v2
         - name: install cargo deps and build avail
           shell: bash
           run: |
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            source "$HOME/.cargo/env"
            cargo build --release -p avail-light
            mv target/release/avail-light target/release/avail-light-linux-amd64
         - uses: actions/upload-artifact@v2
           with:
             name: avail-light-linux-amd64-binary
             path: target/release/avail-light-linux-amd64

  # can extend binary publish 'needs' to include more releases i.e. arm64 in future
  binary_publish:
    needs: [binary_linux_amd64]
    runs-on: ubuntu-latest
    steps:
         - uses: actions/download-artifact@v2
           with:
             name: avail-light-linux-amd64-binary
         - name: Prepare
           id: prepare
           run: |
               TAG=${GITHUB_REF#refs/tags/}
               echo ::set-output name=tag_name::${TAG}
         - name: publish binaries
           uses: svenstaro/upload-release-action@v2
           with:
             repo_token: ${{ secrets.PAT_TOKEN }}
             file: /home/runner/work/avail-light/avail-light/avail-light*
             release_name: ${{ steps.prepare.outputs.tag_name }}
             tag: ${{ steps.prepare.outputs.tag_name }}
             overwrite: true
             file_glob: true
